### ISSUE TITLE
About login page

### ISSUE THREAD

**Issue by Sunnyy001** [yash19sinha/coffee-bean#101]
![Screenshot (28)](https://github.com/yash19sinha/coffee-bean/assets/133258380/18b95359-7267-41bb-babd-1eae92d410c7)

i think the two buttons  cancel and send are not user friendly so i will make it user friendly and more interactive by changing the positions and add will hover effect in it

**Comment by mirza-mohibul-hasan** [comment]
Is that issue solved?

**Comment by yash19sinha** [comment]
The issue has been resolved so I am closing this issue
