### ISSUE TITLE
DOUBLE ESPRESSO image is not available

### ISSUE THREAD

**Issue by abhiinavjain** [yash19sinha/coffee-bean#3]
Hey the website is cool, but DOUBLE ESPRESSO's image is not available. Please assing me this issue I can change it and make it more appealing. 
![image](https://github.com/yash19sinha/coffee-bean/assets/115614480/4de7a8c0-def7-443b-af8f-82cf4cec3204)

**Comment by DavidRod1865** [comment]
I'll like to work on this issue! Please feel free to assign it to me.
