### ISSUE TITLE
small UI error

### ISSUE THREAD

**Issue by bilalmirza74** [yash19sinha/coffee-bean#34]
The yellow and green dots are aligned properly, but the red dot is not.

![image](https://github.com/yash19sinha/coffee-bean/assets/84387676/e9b03bee-96d1-473c-aaeb-fc93d3636ca8)

![image](https://github.com/yash19sinha/coffee-bean/assets/84387676/e7292159-1ed5-4db7-9ba0-25bfc18e0474)

**Comment by anassajaanan** [comment]
I can fix it, can you add me as contributor to this project

**Comment by anassajaanan** [comment]
You can close this issue, I have solved it:  https://github.com/yash19sinha/coffee-bean/pull/43
