### ISSUE TITLE
Updating the Total order Value

### ISSUE THREAD

**Issue by trishit78** [yash19sinha/coffee-bean#56]
in the order section 
The Total Order price needs to be a little larger
<img width="800" alt="image" src="https://github.com/yash19sinha/coffee-bean/assets/90523629/a599556c-3f29-416e-a377-35b96075abc6">
I think it will add more clarity to the user

**Comment by akshaykaluse35** [comment]
Please assign me this, I'm able to do this.....

**Comment by trishit78** [comment]
There are many other bugs in the code base, you can find some other bugs and create issues from that  @akshaykaluse35

**Comment by trishit78** [comment]
Can you assign this issue to me?
@maitri-vv
