### ISSUE TITLE
Dull Color Combination in Navigation bar

### ISSUE THREAD

**Issue by adityamulawekar** [yash19sinha/coffee-bean#68]
![image](https://github.com/yash19sinha/coffee-bean/assets/100304158/55cb61b9-8fb1-4242-bf82-7f8a2ab1a415)
The color combination of the text in the navigation bar is very dull. The text is not visible. As a graphic designer I suggest to change the color that will suit the background and easily readable

**Comment by Chandanmali** [comment]
@yash19sinha can you assign me this issue??
