### ISSUE TITLE
bug: transition is not applied properly for nav links 🙅🏻❌ 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [yash19sinha/coffee-bean#90]
## Description
- Transition is not properly applied for Navigational links during Hover.

## Screenshots 📸 
|||
|:---:|:---:|
|**CURRENT STATE**|![BEFORE](https://github.com/yash19sinha/coffee-bean/assets/92252895/0d0e7a73-4ddf-424b-9da4-61c16ff40b40)|
|**DESIRED STATE**|![AFTER](https://github.com/yash19sinha/coffee-bean/assets/92252895/d73ffa73-05e9-4a56-819b-716c86170cd2)|
|||

**Comment by 0xabdulkhalid** [comment]
Hey there @yash19sinha 👋🏻,

Please make sure to assign this issue to me as soon as possible to make the work done quickly.

Thank you!

**Comment by akshaykaluse35** [comment]
Hey @0xabdulkhalid,Sorry but I've made those changes and submitted the PR.... as I've submitted the issue before you and started working.
